name: Docker Runner - Production

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: self-hosted
    environment: production

    steps:
      - uses: actions/checkout@v4

      - name: Run Container
        run: docker compose -p prod up -d --build
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          LAVALINK_PASSWORD: ${{ secrets.LAVALINK_PASSWORD }}

      - name: Cleanup Unused Images
        run: docker image prune -f

      - name: Cleanup Build Cache
        run: docker builder prune -f --keep-storage 10GB
