name: Docker Container Remove - Development

on: 
  workflow_dispatch:

jobs:
  run:
    runs-on: self-hosted
    environment: development

    steps:
      - uses: actions/checkout@v4

      - name: Remove Container
        run: docker container rm prod -f

      - name: Cleanup Unused Images
        run: docker image prune -f
